Vagrant.configure("2") do |config|
    config.vm.box = "tas50/macos_10.15"
    
    config.vm.box_check_update = false
    
    config.vm.network "public_network"
  
  
    config.vm.synced_folder ".","/vagrant", :disabled =>true
    config.ssh.insert_key=false
  
    config.vm.provider "virtualbox" do|vb|
        vb.memory="4096"
        
        # Fix "hfs mounted macintosh hd on device root_device" issue
        vb.customize ["modifyvm", :id, "--cpuidset", "1","000206a7","02100800","1fbae3bf","bfebfbff"]
  
        # Some more hacks for device recognition
        vb.customize ["setextradata", :id, "VBoxInternal/Devices/efi/0/Config/DmiSystemProduct", "MacBookPro11,3"]
        vb.customize ["setextradata", :id, "VBoxInternal/Devices/efi/0/Config/DmiSystemVersion", "1.0"]
        vb.customize ["setextradata", :id, "VBoxInternal/Devices/efi/0/Config/DmiBoardProduct", "Iloveapple"]
        vb.customize ["setextradata", :id, "VBoxInternal/Devices/smc/0/Config/DeviceKey", "ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc"]
    end

    config.vm.provision "shell", privileged: true, inline: <<-SHELL
    curl -SL -o dotnet-sdk.pkg https://download.visualstudio.microsoft.com/download/pr/81b6b736-1218-4bb0-9100-89945de897be/a2be9ad05a16c0b39c02f2328ccdc6b4/dotnet-sdk-7.0.404-osx-x64.pkg
    mkdir -p $HOME/dotnet && tar zxf dotnet-sdk-7.0.404-osx-x64.pkg -C $HOME/dotnet
    export DOTNET_ROOT=$HOME/dotnet
    export PATH=$PATH:$HOME/dotnet
	dotnet tool install --global VYevseichykLAB4 --version 1.0.0
    SHELL
  end